"""cria tabela de reserva

Revision ID: 747545589852
Revises: e5b193f6c73c
Create Date: 2025-05-24 22:34:03.667416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747545589852'
down_revision: Union[str, None] = 'e5b193f6c73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('viagem_id', sa.Integer(), nullable=False),
    sa.Column('passageiro_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_vagas', sa.Integer(), nullable=False),
    sa.Column('local_partida', sa.String(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'confirmada', 'cancelada', 'finalizada', name='reservastatus'), nullable=False),
    sa.ForeignKeyConstraint(['passageiro_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    # ### end Alembic commands ###
