"""adiciona novo estado no enum

Revision ID: db6429a88499
Revises: 9f9f9a0b7f63
Create Date: 2025-06-05 00:13:19.651848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6429a88499'
down_revision: Union[str, None] = '9f9f9a0b7f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE viagemstatus ADD VALUE 'em_andamento'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
